// Styles inline pour TraceDetailModal.
// Extraits du composant pour reduire sa taille (1311 -> ~770 lignes).
// Aucune modification fonctionnelle, juste un deplacement.

export const S = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(42,26,14,.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: 16,
  },
  modal: {
    background: '#FFFEFB',
    borderRadius: 18,
    width: '100%',
    maxWidth: 560,
    maxHeight: '88vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 24px 60px rgba(42,26,14,.25)',
    overflow: 'hidden',
  },
  hdr: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    padding: '16px 20px 14px',
    borderBottom: '1px solid #EDE7DE',
    background: '#FAF7F2',
  },
  hdrLeft: { display: 'flex', alignItems: 'flex-start', gap: 12 },
  hdrIcon: { display: 'flex', alignItems: 'center', marginTop: 2 },
  hdrTitle: {
    fontFamily: "'Cormorant Garamond', serif",
    fontSize: '1.1rem',
    fontWeight: 700,
    color: '#2A1A0E',
  },
  hdrSub: { fontSize: '.72rem', color: '#9C8878', marginTop: 2 },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    background: 'transparent',
    border: '1.5px solid #EDE7DE',
    color: '#9C8878',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  body: {
    flex: 1,
    overflowY: 'auto',
    padding: '14px 20px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
  },
  preview: {
    width: '100%',
    aspectRatio: '4 / 3',
    background: '#EDE7DE',
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  previewImg: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    objectFit: 'contain',
    display: 'block',
    borderRadius: 10,
  },
  statusRow: { display: 'flex', alignItems: 'center', gap: 8 },
  statusDot: { width: 10, height: 10, borderRadius: '50%', flexShrink: 0 },
  statusLabel: {
    fontSize: '.76rem',
    color: '#9C8878',
    fontFamily: "'Nunito', sans-serif",
    fontWeight: 600,
  },
  responses: { display: 'flex', flexDirection: 'column', gap: 12 },
  respBlock: { display: 'flex', flexDirection: 'column', gap: 4 },
  respHead: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  respLabel: {
    fontSize: '.7rem',
    color: '#9C8878',
    fontFamily: "'Nunito', sans-serif",
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '.05em',
    flex: 1,
  },
  editIconBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 24,
    height: 24,
    background: 'transparent',
    border: 'none',
    borderRadius: 6,
    color: '#8B6445',
    transition: 'opacity .15s ease',
    padding: 0,
    flexShrink: 0,
  },
  respText: {
    fontFamily: "'Lora', serif",
    fontStyle: 'italic',
    fontSize: '.88rem',
    color: '#2A1A0E',
    lineHeight: 1.7,
    margin: 0,
  },
  respEmpty: {
    fontFamily: "'Lora', serif",
    fontStyle: 'italic',
    fontSize: '.82rem',
    color: '#B0A090',
    lineHeight: 1.6,
    margin: 0,
  },
  editBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    marginTop: 2,
  },
  textarea: {
    width: '100%',
    minHeight: 88,
    padding: '10px 12px',
    fontFamily: "'Lora', serif",
    fontSize: '.9rem',
    color: '#2A1A0E',
    lineHeight: 1.6,
    background: '#FFFEFB',
    border: '1.5px solid #D8C9B8',
    borderRadius: 10,
    outline: 'none',
    resize: 'vertical',
    boxSizing: 'border-box',
  },
  editActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'flex-end',
  },
  cancelBtn: {
    padding: '7px 14px',
    background: 'transparent',
    border: '1.5px solid #EDE7DE',
    borderRadius: 10,
    fontSize: '.76rem',
    fontWeight: 600,
    fontFamily: "'Nunito', sans-serif",
    color: '#9C8878',
    cursor: 'pointer',
  },
  saveBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '7px 14px',
    background: '#8B6445',
    border: '1.5px solid #8B6445',
    borderRadius: 10,
    fontSize: '.76rem',
    fontWeight: 700,
    fontFamily: "'Nunito', sans-serif",
    color: '#FFFEFB',
    cursor: 'pointer',
  },
  footer: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '12px 20px',
    borderTop: '1px solid #EDE7DE',
    background: '#FAF7F2',
    flexWrap: 'wrap',
  },
  // Lot B — Rattachement chapitre
  chapterRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    width: '100%',
    marginBottom: 4,
  },
  chapterSelect: {
    flex: 1,
    padding: '6px 10px',
    fontFamily: "'Nunito', sans-serif",
    fontSize: '.76rem',
    fontWeight: 600,
    color: '#2A1A0E',
    background: '#FFFEFB',
    border: '1.5px solid #EDE7DE',
    borderRadius: 10,
    outline: 'none',
    appearance: 'auto',
  },
  actionBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 12px',
    background: '#FFFEFB',
    border: '1.5px solid #EDE7DE',
    borderRadius: 10,
    fontSize: '.76rem',
    fontWeight: 600,
    fontFamily: "'Nunito', sans-serif",
    color: '#8B6445',
    cursor: 'pointer',
  },
  statusDropdown: {
    position: 'absolute',
    bottom: 'calc(100% + 6px)',
    left: 0,
    background: '#FFFEFB',
    border: '1px solid #EDE7DE',
    borderRadius: 12,
    boxShadow: '0 8px 28px rgba(42,26,14,.14)',
    padding: '6px',
    zIndex: 50,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    width: 230,
    animation: 'slideUp .18s ease',
  },
  statusOption: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '8px 10px',
    background: 'transparent',
    border: '1.5px solid transparent',
    borderRadius: 8,
    fontSize: '.78rem',
    fontWeight: 600,
    fontFamily: "'Nunito', sans-serif",
    color: '#2A1A0E',
    cursor: 'pointer',
    textAlign: 'left',
    width: '100%',
    transition: 'background .12s ease',
  },
  statusOptionCurrent: {
    background: '#F5F0E8',
    borderColor: '#D8C9B8',
  },
  statusOptionLabel: { flex: 1 },
  statusCheck: { color: '#6B8F71', flexShrink: 0 },
  // FEAT-F — Bandeau apiKey absent
  noApiKeyHint: {
    padding: '10px 14px',
    background: '#FAF7F2',
    border: '1px solid #EDE7DE',
    borderRadius: 12,
  },
  noApiKeyText: {
    margin: 0,
    fontFamily: "'Lora', serif",
    fontStyle: 'italic',
    fontSize: '.82rem',
    color: '#7A6555',
    lineHeight: 1.5,
  },
  // FEAT-E — CTA primaire "Continuer avec Léa"
  continueBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 14px',
    background: '#8B6445',
    color: '#FFFEFB',
    border: '1.5px solid #8B6445',
    borderRadius: 10,
    fontSize: '.78rem',
    fontWeight: 700,
    fontFamily: "'Nunito', sans-serif",
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(139,100,69,.15)',
  },
  deleteBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
    marginLeft: 'auto',
    background: 'transparent',
    border: '1.5px solid #EDE7DE',
    borderRadius: 10,
    color: '#B0A090',
    cursor: 'pointer',
  },
  ocrBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  visionBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    padding: '8px 14px',
    background: 'transparent',
    color: '#7A6555',
    border: '1.5px solid #D4B896',
    borderRadius: 10,
    fontSize: '.82rem',
    fontWeight: 600,
    fontFamily: "'Nunito', sans-serif",
    cursor: 'pointer',
    alignSelf: 'flex-start',
  },
  visionBtnSecondary: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 12px',
    background: 'transparent',
    color: '#7A6555',
    border: '1.5px solid #D4B896',
    borderRadius: 10,
    fontSize: '.76rem',
    fontWeight: 600,
    fontFamily: "'Nunito', sans-serif",
    cursor: 'pointer',
  },
  ocrRunning: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    background: '#F5F0E8',
    border: '1px solid #EDE7DE',
    borderRadius: 10,
    fontFamily: "'Lora', serif",
    fontStyle: 'italic',
    fontSize: '.82rem',
    color: '#7A6555',
  },
  ocrPreview: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: '12px 14px',
    background: '#F5F0E8',
    border: '1px solid #D4B896',
    borderRadius: 12,
  },
  ocrPreviewLabel: {
    margin: 0,
    fontFamily: "'Nunito', sans-serif",
    fontSize: '.7rem',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '.05em',
    color: '#7A6555',
  },
  ocrPreviewText: {
    margin: 0,
    fontFamily: "'Lora', serif",
    fontStyle: 'italic',
    fontSize: '.88rem',
    color: '#2A1A0E',
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap',
  },
  ocrPreviewActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'flex-end',
  },
  ocrErrRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '8px 12px',
    background: '#FEF0F0',
    border: '1px solid #E8A0A0',
    borderRadius: 10,
  },
  ocrErrMsg: {
    margin: 0,
    flex: 1,
    fontFamily: "'Nunito', sans-serif",
    fontSize: '.78rem',
    color: '#8B2020',
  },
  linkBtn: {
    background: 'transparent',
    border: 'none',
    color: '#8B6445',
    fontSize: '.78rem',
    fontWeight: 700,
    fontFamily: "'Nunito', sans-serif",
    cursor: 'pointer',
    padding: 0,
    textDecoration: 'underline',
  },
  ocrSaved: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: '12px 14px',
    background: '#FAF7F2',
    border: '1px solid #EDE7DE',
    borderRadius: 12,
  },
  ocrSavedLabel: {
    margin: 0,
    fontFamily: "'Nunito', sans-serif",
    fontSize: '.7rem',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '.05em',
    color: '#9C8878',
  },
  ocrSavedText: {
    margin: 0,
    fontFamily: "'Lora', serif",
    fontStyle: 'italic',
    fontSize: '.86rem',
    color: '#2A1A0E',
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap',
  },
  ocrSavedActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'flex-end',
  },
  inspireBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: '12px 14px',
    background: '#FFFEFB',
    border: '1.5px solid #E7D6BF',
    borderRadius: 14,
  },
  inspireIntro: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  inspireTitle: {
    margin: 0,
    fontFamily: "'Cormorant Garamond', serif",
    fontSize: '1rem',
    fontWeight: 700,
    color: '#6E3A1E',
  },
  inspireHint: {
    margin: '3px 0 0',
    fontFamily: "'Lora', serif",
    fontStyle: 'italic',
    fontSize: '.82rem',
    lineHeight: 1.55,
    color: '#7A6555',
  },
  inspireBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    padding: '8px 14px',
    background: '#F5F0E8',
    color: '#6E3A1E',
    border: '1.5px solid #D4B896',
    borderRadius: 10,
    fontSize: '.82rem',
    fontWeight: 700,
    fontFamily: "'Nunito', sans-serif",
    cursor: 'pointer',
    alignSelf: 'flex-start',
  },
  inspireRunning: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    background: '#F5F0E8',
    borderRadius: 10,
    fontFamily: "'Lora', serif",
    fontStyle: 'italic',
    fontSize: '.82rem',
    color: '#7A6555',
  },
  inspireResult: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  inspireResultLabel: {
    margin: 0,
    fontFamily: "'Nunito', sans-serif",
    fontSize: '.7rem',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '.05em',
    color: '#7A6555',
  },
  inspireResultText: {
    margin: 0,
    fontFamily: "'Lora', serif",
    fontSize: '.88rem',
    color: '#2A1A0E',
    lineHeight: 1.65,
    whiteSpace: 'pre-wrap',
  },
  inspireActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
  },
}
